### ISSUE TITLE
browser is not defined

### ISSUE THREAD

**Issue by HermanNygaard** [tanettrimas/finn-pris-per-kvadratmeter#64]
Hei, takk for kul extension! Men den fungerer ikke etter den nye versjonen hos meg:
![image](https://user-images.githubusercontent.com/20663884/129581647-6b9fd5e1-b510-41de-a3f1-a4cc90602c44.png)

**Comment by tanettrimas** [comment]
Hei @HermanNygaard :) 

Regner med du får denne i chrome. Hvilken versjon av chrome har du? Det kan være pga av en polyfill som mangler, men vil gjerne sjekke det ved å teste mot din versjon. Det skal uansett fungere med firefox, så har du en workaround inntil videre :)

**Comment by HermanNygaard** [comment]
Takk for raskt svar, jeg bruker vanlig Google Chrome versjon `92.0.4515.131 (Official Build) (x86_64)`
Men det fungerte på Firefox 👍

**Comment by tanettrimas** [comment]
@HermanNygaard Shipper ut en bugfix med en ny release som skal fikse dette. Regner med at ny versjon er ute i løpet av uken.

**Comment by tanettrimas** [comment]
Da er ny versjon publisert og venter på review. Ny versjon vil være 1.0.16 :)
